language: node_js
sudo: false
services:
- mongodb
node_js:
- "6"
cache:
  directories:
  - node_modules
  - public/build
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
script:
  - npm test
